name: Tests

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ["8.2", "8.4", "8.5"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: Update dependencies
              run: composer update --no-interaction --prefer-dist

            - name: Validate Composer config
              run: composer validate --no-check-publish

            - name: Run tests
              run: composer test
